"""Season-facing metadata helpers for standings payloads."""

DRIVER_NUMBERS = {
    "VER": 1,
    "NOR": 4,
    "LEC": 16,
    "SAI": 55,
    "HAM": 44,
    "RUS": 63,
    "PIA": 81,
    "ALO": 14,
    "STR": 18,
    "GAS": 10,
    "OCO": 31,
    "ALB": 23,
    "TSU": 22,
    "RIC": 3,
    "HUL": 27,
    "MAG": 20,
    "BOT": 77,
    "ZHO": 24,
    "SAR": 2,
    "LAW": 30,
    "BEA": 87,
    "COL": 43,
    "DOO": 7,
    "ANT": 12,
    "HAD": 6,
    "BOR": 5,
}

TEAM_ID_MAP = {
    "McLaren": "mclaren",
    "Ferrari": "ferrari",
    "Red Bull": "red_bull",
    "Mercedes": "mercedes",
    "Aston Martin": "aston_martin",
    "Alpine": "alpine",
    "Williams": "williams",
    "RB": "racing_bulls",
    "Racing Bulls": "racing_bulls",
    "Haas F1 Team": "haas",
    "Haas": "haas",
    "Kick Sauber": "sauber",
    "Sauber": "sauber",
    "Alfa Romeo": "sauber",
}
